### ISSUE TITLE
Dataset Configuration Questions:

### ISSUE THREAD

**Issue by rungjoo** [eth-sri/ChatProtect#3]
1. `folder_list = glob.glob("test/test/sentences/gpt4/*/m3")`  
   I understand that this data corresponds to the **MainTestSet**, and the tags represent the labels. Are these labels manually annotated?  
   Does "ok" mean **no contradiction**, and does "strong" mean **contradiction**?

2-1. `file_list = glob.glob("output/test/gpt4/gpt4/s3/test_m3/*")`  
   This data contains more entries than the **MainTestSet**. 
   For example, it includes `test/test/sentences/gpt4/Please_tell_me_about_199091_Austrian_Hockey_League_season`, which isn't included in the MainTestSet(`"test/test/sentences/gpt4/*/m3"`). 
What are these additional data?
   
2-2. What does the following mean among the data available here?

   ```json
   {"Q": "Please conclude whether the statements are contradictory with Yes or No.", "A": ["No", "No", "No", "No", "No", "No", "No", "No", "No", "No"]}
   ```  
   In this case, "No" appears 10 times. What do these 10 iterations represent?

3. Where can I find the **2ndTestSet**?

**Comment by nielstron** [comment]
Thank you for reaching out!

1. Correct. This data corresponds to the MainTestSet and the labels **tag** are manually annotated, where you correctly noticed that "ok" means no contradiction, "strong" means contradiction. 
2. Second question
   1.  I am not sure what you are referring to here? The entity you mention is included in the MainTestSet, see `test/test/sentences/gpt4/Please_tell_me_about_199091_Austrian_Hockey_League_season/`
   2. The 10 repetitions are 10 sampled responses from the API. They were used to compute scores for the comparison with SelfCheckGPT in Figure 6a). However we found that this implicit score contained very little variance and ultimately pivoted to an explicit model score between 1 and 10, which resulted in more fine grained results.
1. The second test set is to be found in `test/test_big`

**Comment by rungjoo** [comment]
Thank you very much for your answer. I understood the explanation well.

Question 2-1 was my mistake.
If I have any other questions, I will ask.
